COLUMNS:
  house_type: int64
  location: int64
  numBathrooms: float64
  numBalconies: float64
  isNegotiable: int64
  verificationDate: float64
  SecurityDeposit: int64
  Status: int64
  bhk: int64
  house_size_sqft: int64
  city: int64
TARGET_COLUMN:
  name: price